version: '3.6'

services:
  velib_api:
    build: .
    command: sh -c 'sleep 3; python velib_api.py --init'
    networks:
      - common-net
    env_file:
      - .env
  db:
    image: postgres:alpine3.16
    hostname: postgres
    ports: 
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./dbData/:/var/lib/postgresql/data
    networks:
      - common-net

networks:
  common-net: 
